#!/usr/bin/env node

/**
 * Auto Version Bump Script
 *
 * Triggered by post-commit hook. Analyzes commit message and:
 *   feat: → bumps MINOR (1.0.0 → 1.1.0)
 *   fix:  → bumps PATCH (1.0.0 → 1.0.1)
 *   other → no bump
 *
 * Creates a "chore: release" commit with updated version files.
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

try {
  // 1. Get the last commit message and hash
  const lastCommitMsg = execSync('git log -1 --pretty=%B').toString().trim();
  const lastCommitHash = execSync('git rev-parse --short HEAD').toString().trim();

  // 🛡️ SAFETY: Prevent Infinite Loops
  if (lastCommitMsg.startsWith('chore: release') || lastCommitMsg.startsWith('chore(release)')) {
    process.exit(0);
  }

  // Skip merge commits
  if (lastCommitMsg.startsWith('Merge')) {
    process.exit(0);
  }

  console.log('\n🔍 Analyzing commit for version bump...');

  // 2. Determine Bump Type
  let bumpType = null;
  const firstLine = lastCommitMsg.split('\n')[0].toLowerCase();

  // Breaking change = MAJOR
  if (firstLine.includes('!:') || lastCommitMsg.includes('BREAKING CHANGE')) {
    bumpType = 'major';
  }
  // Feature = MINOR
  else if (firstLine.startsWith('feat:') || firstLine.startsWith('feat(')) {
    bumpType = 'minor';
  }
  // Fix/perf = PATCH
  else if (
    firstLine.startsWith('fix:') ||
    firstLine.startsWith('fix(') ||
    firstLine.startsWith('perf:') ||
    firstLine.startsWith('perf(')
  ) {
    bumpType = 'patch';
  }

  if (!bumpType) {
    console.log('ℹ️  No version bump needed (not feat/fix/perf)');
    process.exit(0);
  }

  // 3. Bump npm version (updates package.json & package-lock.json)
  console.log(`🚀 Bumping ${bumpType.toUpperCase()} version...`);
  execSync(`npm version ${bumpType} --no-git-tag-version`, { stdio: 'inherit' });

  // 4. Read the NEW version and sync to dashboard
  const rootPkg = require('../package.json');
  const newVersion = rootPkg.version;

  // Update dashboard/package.json to match
  const dashboardPkgPath = path.join(__dirname, '../dashboard/package.json');
  const dashboardPkg = JSON.parse(fs.readFileSync(dashboardPkgPath, 'utf8'));
  dashboardPkg.version = newVersion;
  fs.writeFileSync(dashboardPkgPath, JSON.stringify(dashboardPkg, null, 2) + '\n');

  // 5. Generate version.ts for dashboard
  generateVersionFile(lastCommitHash, newVersion);

  // 6. Stage all version-related files
  console.log('💾 Staging version files...');
  execSync('git add package.json package-lock.json dashboard/package.json dashboard/lib/version.ts');

  // 7. Create the release commit (with [skip ci] to prevent double-deploy)
  execSync(`git commit --no-verify -m "chore: release v${newVersion} [skip ci]"`, {
    stdio: 'inherit',
  });

  console.log(`\n✅ Successfully bumped to v${newVersion}`);
  console.log(`   Commit: ${lastCommitHash} (${firstLine.substring(0, 50)}...)`);
  console.log('');

} catch (error) {
  console.error('❌ Auto-bump failed:', error.message);
  process.exit(1);
}

/**
 * Generate dashboard/lib/version.ts
 */
function generateVersionFile(commitHash, version = null) {
  // If no version provided, read from package.json
  if (!version) {
    try {
      const pkg = require('../package.json');
      version = pkg.version;
    } catch {
      version = '0.0.0';
    }
  }

  const buildDate = new Date().toISOString();

  const content = `/**
 * THIS FILE IS AUTO-GENERATED - DO NOT EDIT
 * Generated by: scripts/auto-bump.js
 * Timestamp: ${buildDate}
 */

/** App version from package.json */
export const APP_VERSION = '${version}';

/** Git commit hash that triggered this version */
export const BUILD_COMMIT = '${commitHash}';

/** ISO timestamp of build */
export const BUILD_DATE = '${buildDate}';

/** Display string: "v1.2.0 (a1b2c3d)" */
export const VERSION_STRING = \`v\${APP_VERSION} (\${BUILD_COMMIT})\`;

/** Build info object for debugging */
export const BUILD_INFO = {
  version: APP_VERSION,
  commit: BUILD_COMMIT,
  date: BUILD_DATE,
} as const;
`;

  const outputDir = path.join(__dirname, '../dashboard/lib');
  const outputPath = path.join(outputDir, 'version.ts');

  // Ensure directory exists
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  fs.writeFileSync(outputPath, content);
  console.log(`📝 Updated dashboard/lib/version.ts`);
}
